### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Kautenja** [Kautenja/PotatoChips#14]
APU code has been pulled from [blargg's libraries](https://www.slack.net/~ant/libs/audio.html) for the chips below:

- [x] Ricoh 2A03 (Nintendo NES)
- [x] Konami VRC6 (Nintendo NES)
- [x] Sunsoft FME7 (Nintendo NES)
- [x] Namco 106 (Nintendo NES)
- [x] Nintendo GBS (Gameboy)
    - convert DPCM to wavetable voice
- [ ] Sony S-SMP (Nintendo SNES)
    - echo effect
    - sampler module?
    - convert to wavetable voices?
- [ ] Yamaha YM2413 (Sega Master Sysem)
- [x] Yamaha YM2612 (Sega Mega Drive)
- [x] Texas Instruments SN76489 (Sega Master System)
- [ ] Konami SCC
- [x] General Instrument Ay-3-8910
- [x] Atari Pokey
- [ ] NEC Turbo Grafx 16

**Comment by Kautenja** [comment]
~~A good YM2612 module (CV2612) already exists based on the code that was forked into this repo from Blargg's resources: https://github.com/diegodorado/TercerBrazo~~

~~If their module isn't updated for future versions of VCV Rack, I'll fork it into this repository and maintain it, but for now there is no need to work on an emulation of this chip. Their module may prove a nice baseline for setting up the YM2413 module, however.~~

2612 was introduced in version 1.7.0. It fixes some bugs that are in CV2612 and changes the polyphony model and panel layout.

**Comment by Kautenja** [comment]
~~As a sidenote, it might be cool to clone the Twisted Electrons MegaFM as a Eurorack module. It uses two YM2612 chips for 12-voices of FM.~~

2612 allows for 6 VOCT and gate inputs for each of the voices on the chip. A MegaFM can now be patched up using two 2612 modules and 3 external LFOs / envelope generators patched to various parameters. :)

**Comment by Kautenja** [comment]
It would be good to implement access to the sweep parameters and the envelope parameters for the chips that have these features.

**Comment by Kautenja** [comment]
https://community.vcvrack.com/t/potato-chips-opinions-on-wavetable-synthesis/10657/18 is tracking ideas for the SCC and TurboGrafx16 emulation-based modules!

**Comment by Kautenja** [comment]
#58, #59, #60, and #61 now document the roadmap for the final four modules (TurboGrafx16, SCC, YM2413, S-SMP). Closing issue as those now track the roadmap.
